package store

import "time"

// Config is the persisted desired-state of every WireGuard interface.
type Config struct {
	Version    int          `json:"version"`
	Settings   Settings     `json:"settings"`
	Interfaces []*Interface `json:"interfaces"`
}

// Settings holds daemon-wide configuration.
type Settings struct {
	// PublicEndpoint is the externally reachable endpoint of this server
	// (host or host:port). The listen port is appended when omitted. It is
	// embedded into client configuration files as [Peer] Endpoint.
	PublicEndpoint string `json:"publicEndpoint"`
}

// Interface describes a single WireGuard interface.
type Interface struct {
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"`
	// PrivateKey never leaves the server.
	PrivateKey string    `json:"privateKey"`
	ListenPort int       `json:"listenPort"`
	Addresses  []string  `json:"addresses"`
	MTU        int       `json:"mtu"`
	DNS        []string  `json:"dns"`
	Up         bool      `json:"up"`
	Peers      []*Peer   `json:"peers"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// Peer describes a WireGuard peer.
type Peer struct {
	// Name is a short human-readable label.
	Name string `json:"name"`
	// PublicKey identifies the peer inside WireGuard.
	PublicKey string `json:"publicKey"`
	// PrivateKey is the client keypair generated by this tool, kept so the
	// client configuration file / QR code can be (re)produced. It is never
	// needed on the server data path but is stored here for convenience.
	PrivateKey string `json:"privateKey,omitempty"`
	// PresharedKey is optional and enabled per peer.
	PresharedKey string `json:"presharedKey,omitempty"`
	// Address is the tunnel address assigned to this peer (the /32 entry of
	// the server AllowedIPs list). Filled automatically if left blank.
	Address string `json:"address"`
	// AllowedIPs are the addresses this peer is allowed to claim on the
	// server side.
	AllowedIPs []string `json:"allowedIPs"`
	// ClientRoutes are the routes pushed into the client config file.
	ClientRoutes []string `json:"clientRoutes,omitempty"`
	// DNS servers pushed to the client.
	DNS []string `json:"dns,omitempty"`
	// Endpoint is the client's known endpoint (optional).
	Endpoint string `json:"endpoint,omitempty"`
	// PersistentKeepalive interval in seconds (0 to disable).
	PersistentKeepalive int       `json:"persistentKeepalive"`
	Description         string    `json:"description,omitempty"`
	Enabled             bool      `json:"enabled"`
	CreatedAt           time.Time `json:"createdAt"`
	UpdatedAt           time.Time `json:"updatedAt"`
}
